#!/usr/bin/env python3
"""Reviewer-owned exact algebra and exhaustive finite-cell controls. No samples."""
import json
from fractions import Fraction
from pathlib import Path
import sympy as sp

checks = []
def eq(name, left, right=0):
    residual = sp.factor(sp.powsimp(sp.simplify(left-right)))
    if residual != 0:
        # The geometric domain has z=x+y-xy>0. SymPy does not infer
        # that from unrestricted positive x,y. Expose the positive base,
        # simplify, then restore its exact value without a forced power rule.
        Z=sp.Symbol('Z_positive', positive=True)
        residual=sp.simplify(sp.simplify((left-right).subs(x+y-x*y,Z)).subs(Z,x+y-x*y))
    assert residual == 0, (name, residual)
    checks.append({'name':name,'status':'PASS','method':'exact symbolic identity'})

x,y,c=sp.symbols('x y c',positive=True)
n,m=sp.symbols('n m',integer=True,positive=True)
z=x+y-x*y
S=x**c+y**c-z**c
sx=sp.diff(S,x)
sy=sp.diff(S,y)
sxy=sp.diff(S,x,y)
eq('Direct S_x derivative',sx,c*(x**(c-1)-(1-y)*z**(c-1)))
eq('Direct S_y derivative',sy,c*(y**(c-1)-(1-x)*z**(c-1)))
eq('Direct mixed S derivative',sxy,c*z**(c-2)*(1-c*(1-x)*(1-y)))
eq('S grounded at x=0',S.subs(x,0))
eq('S grounded at y=0',S.subs(y,0))
eq('S right margin',S.subs(y,1),x**c)
eq('S top margin',S.subs(x,1),y**c)
eq('c=1 equality control',S.subs(c,1),x*y)
eq('Density constant',((m*(m-1)*c**2+m*c).subs({m:n+1,c:n/(n+1)})),n**2+n/(n+1))
eq('n=1 density constant',(n**2+n/(n+1)).subs(n,1),sp.Rational(3,2))

# Check chain rule using an unrelated formal positive bivariate function.
Q=sp.Function('Q',positive=True)(x,y)
eq('Power-CDF density chain rule',sp.diff(Q**m,x,y),m*(m-1)*Q**(m-2)*sp.diff(Q,x)*sp.diff(Q,y)+m*Q**(m-1)*sp.diff(Q,x,y))

# Independent one-dimensional reduction M=max(X,Y).
r=sp.symbols('r',positive=True)
A=sp.Function('A')(r)
eq('One-dimensional max-density derivative',sp.diff(r**n*A,r),n*r**(n-1)*A+r**n*sp.diff(A,r))
lam=sp.symbols('lambda',positive=True)
eq('Logarithmic L2 divergence integrand',(n*lam*r**(n-1))**2/(2*n*r**(2*n-1)),n*lam**2/(2*r))

h,t,a,b=sp.symbols('h t a b',positive=True)
eq('Shell cancellation',(t*(a-h*b))**2/(t**2*(1-h**2)),(a-h*b)**2/(1-h**2))
eq('Limiting shell contribution',(lam-h*lam)**2/(1-h**2),lam**2*(1-h)/(1+h))
eq('Monotone L shell decomposition',a-h*b,(a-b)+(1-h)*b)

# Exact rational form of the log-moment integral after u=-log(x).
u=sp.symbols('u',nonnegative=True)
eq('Beta log moment',sp.integrate(n*u*sp.exp(-n*u),(u,0,sp.oo)),1/n)
eq('n=1 limiting shell constant',(lam**2*(1-h)/(1+h)).subs({lam:(2-sp.sqrt(2))**2,h:sp.Rational(1,2)}),(2-sp.sqrt(2))**4/3)

# Cover every open rectangular atom generated by the K thresholds.
# Boundary equalities are null under both continuously distributed margins.
cases=0
for K in range(1,9):
    bounds=[Fraction(1,2**k) for k in range(K+1)]+[Fraction(0)]
    mids=[(bounds[j]+bounds[j+1])/2 for j in range(K+1)]
    for ix,xval in enumerate(mids):
        for iy,yval in enumerate(mids):
            probes=[(xval < bounds[k], yval < bounds[k]) for k in range(1,K+1)]
            decoded=sum(int(ax and by) for ax,by in probes)
            assert decoded == min(ix,iy)
            maxval=max(xval,yval)
            assert bounds[decoded+1] < maxval < bounds[decoded]
            cases += 1
checks.append({'name':'2K face bits decode all dyadic open grid atoms for K=1..8','status':'PASS','method':'exhaustive exact-rational combinatorial check','cases':cases})

result={'status':'PASS','scope':'Exact symbolic and finite combinatorial controls; no empirical validation, no numerical integration, no sampling, no author-code import or replay. Analytic inequalities and limiting arguments are reviewed in REVIEW.md.','sympy_version':sp.__version__,'checks':checks,'check_count':len(checks)}
print(json.dumps(result,indent=2))
