#!/usr/bin/env python3
import json, random
from pathlib import Path

SEED=11092026
rng=random.Random(SEED)

def canon(vals):
    d={};out=[]
    for x in vals:
        if x not in d:d[x]=len(d)
        out.append(d[x])
    return tuple(out)
def randpart(n):return canon([rng.randrange(1+rng.randrange(n)) for _ in range(n)])
def joint(a,b):return canon(list(zip(a,b)))
def fibres(p):
    d={}
    for i,x in enumerate(p):d.setdefault(x,set()).add(i)
    return list(d.values())
def refines(p,q):return all(len({q[i] for i in c})==1 for c in fibres(p))
def suff(E,r,Q):return refines(joint(E,r),Q)
def weaker(E,r,s):return refines(joint(E,s),joint(E,r))

def relabel(p):
    labels=list(set(p)); shuffled=labels[:];rng.shuffle(shuffled)
    m=dict(zip(labels,shuffled));return tuple(m[x] for x in p)

def main():
    trials=50000; failures=[]; empties=nonunique=0; relabel_fail=0
    for t in range(trials):
        n=rng.randint(3,8);E=randpart(n);Q=randpart(n)
        C=[randpart(n) for _ in range(rng.randint(1,10))]
        D=[r for r in C if suff(E,r,Q)]
        if not D:empties+=1
        mins=[r for r in D if not any(s!=r and weaker(E,s,r) and not weaker(E,r,s) for s in D)]
        if D and not mins:failures.append(('no_min',t))
        if len({joint(E,r) for r in mins})>1:nonunique+=1
        # All sufficient candidates refine the unrestricted floor E∧Q.
        floor=joint(E,Q)
        if any(not refines(joint(E,r),floor) for r in D):failures.append(('floor',t))
        # Any postprocessing of E generated by relabel/coarsening E cannot split a Q conflict.
        r=relabel(E)
        if not refines(E,Q) and suff(E,r,Q):failures.append(('post',t))
        # label renaming must not change sufficiency
        if C:
            c=C[0]
            if suff(E,c,Q)!=suff(relabel(E),relabel(c),relabel(Q)):
                relabel_fail+=1
        if len(failures)>=3:break
    result={'seed':SEED,'random_candidate_family_trials':trials,
      'empty_candidate_discriminator_sets':empties,
      'nonunique_partition_minima':nonunique,
      'failures':len(failures),'first_failures':failures,
      'relabel_invariance_failures':relabel_fail,
      'overall':'PASS' if not failures and relabel_fail==0 and empties>0 and nonunique>0 else 'FAIL'}
    out=Path(__file__).with_name(Path(__file__).stem+'_results.json')
    out.write_text(json.dumps(result,indent=2,sort_keys=True)+'\n')
    print(json.dumps(result,indent=2,sort_keys=True))
if __name__=='__main__':main()
